package com.roy.mapper;

import com.roy.model.ChatInfo;
import com.roy.model.ChatInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    long countByExample(ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int deleteByExample(ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int insert(ChatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int insertSelective(ChatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    List<ChatInfo> selectByExample(ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    ChatInfo selectByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatInfo record, @Param("example") ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatInfo record, @Param("example") ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatInfo record);
}