package com.roy.mapper;

import com.roy.model.Subgroup;
import com.roy.model.SubgroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    long countByExample(SubgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int deleteByExample(SubgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int insert(Subgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int insertSelective(Subgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    List<Subgroup> selectByExample(SubgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    Subgroup selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Subgroup record, @Param("example") SubgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Subgroup record, @Param("example") SubgroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Subgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Subgroup record);
}