package org.sang.mapper;

import org.sang.bean.ChatMsg;
import org.sang.bean.ChatMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    long countByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int deleteByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int insert(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int insertSelective(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    List<ChatMsg> selectByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    ChatMsg selectByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatMsg record, @Param("example") ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatMsg record, @Param("example") ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatmsg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatMsg record);

    int markRead(@Param("isread")int isread,@Param("sendId")Long sendId,@Param("receivId") Long receivId);

    List<ChatMsg> selectByPage(@Param("start")Integer start,@Param("size") Integer size,@Param("rid") Long rid,@Param("sid") Long sid);
}