package org.sang.bean;

import org.sang.mapper.ChatMsgMapper;
import org.sang.mapper.HrMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class ChatMsg {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.cId
     *
     * @mbg.generated
     */
    private Long cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.sendId
     *
     * @mbg.generated
     */
    private Long sendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.receivId
     *
     * @mbg.generated
     */
    private Long receivid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.sendTime
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.isread
     *
     * @mbg.generated
     */
    private Boolean isread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chatmsg.attach
     *
     * @mbg.generated
     */
    private String attach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.cId
     *
     * @return the value of chatmsg.cId
     *
     * @mbg.generated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.cId
     *
     * @param cid the value for chatmsg.cId
     *
     * @mbg.generated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.sendId
     *
     * @return the value of chatmsg.sendId
     *
     * @mbg.generated
     */
    public Long getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.sendId
     *
     * @param sendid the value for chatmsg.sendId
     *
     * @mbg.generated
     */
    public void setSendid(Long sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.receivId
     *
     * @return the value of chatmsg.receivId
     *
     * @mbg.generated
     */
    public Long getReceivid() {
        return receivid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.receivId
     *
     * @param receivid the value for chatmsg.receivId
     *
     * @mbg.generated
     */
    public void setReceivid(Long receivid) {
        this.receivid = receivid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.message
     *
     * @return the value of chatmsg.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.message
     *
     * @param message the value for chatmsg.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.sendTime
     *
     * @return the value of chatmsg.sendTime
     *
     * @mbg.generated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.sendTime
     *
     * @param sendtime the value for chatmsg.sendTime
     *
     * @mbg.generated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.isread
     *
     * @return the value of chatmsg.isread
     *
     * @mbg.generated
     */
    public Boolean getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.isread
     *
     * @param isread the value for chatmsg.isread
     *
     * @mbg.generated
     */
    public void setIsread(Boolean isread) {
        this.isread = isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.status
     *
     * @return the value of chatmsg.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.status
     *
     * @param status the value for chatmsg.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chatmsg.attach
     *
     * @return the value of chatmsg.attach
     *
     * @mbg.generated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chatmsg.attach
     *
     * @param attach the value for chatmsg.attach
     *
     * @mbg.generated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }


    private String sendUserName;

    public String getSendUserName() {
        return sendUserName;
    }

    public void setSendUserName(String sendUserName) {
        this.sendUserName = sendUserName;
    }
    private String receivedUserName;

    public String getReceivedUserName() {
        return receivedUserName;
    }

    public void setReceivedUserName(String receivedUserName) {
        this.receivedUserName = receivedUserName;
    }

    @Override
    public String toString() {
        return "ChatMsg{" +
                "cid=" + cid +
                ", sendid=" + sendid +
                ", receivid=" + receivid +
                ", message='" + message + '\'' +
                ", sendtime=" + sendtime +
                ", isread=" + isread +
                ", status=" + status +
                ", attach='" + attach + '\'' +
                ", sendUserName='" + sendUserName + '\'' +
                ", receivedUserName='" + receivedUserName + '\'' +
                '}';
    }
}