package com.roy.model;

import java.io.Serializable;
import java.util.Date;

public class SubGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subgroup.sid
     *
     * @mbg.generated
     */
    private Long sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subgroup.qno
     *
     * @mbg.generated
     */
    private Long qno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subgroup.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subgroup.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subgroup.attach
     *
     * @mbg.generated
     */
    private String attach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subgroup.sid
     *
     * @return the value of subgroup.sid
     *
     * @mbg.generated
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subgroup.sid
     *
     * @param sid the value for subgroup.sid
     *
     * @mbg.generated
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subgroup.qno
     *
     * @return the value of subgroup.qno
     *
     * @mbg.generated
     */
    public Long getQno() {
        return qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subgroup.qno
     *
     * @param qno the value for subgroup.qno
     *
     * @mbg.generated
     */
    public void setQno(Long qno) {
        this.qno = qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subgroup.sname
     *
     * @return the value of subgroup.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subgroup.sname
     *
     * @param sname the value for subgroup.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subgroup.create_time
     *
     * @return the value of subgroup.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subgroup.create_time
     *
     * @param createTime the value for subgroup.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subgroup.attach
     *
     * @return the value of subgroup.attach
     *
     * @mbg.generated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subgroup.attach
     *
     * @param attach the value for subgroup.attach
     *
     * @mbg.generated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }

    @Override
    public String toString() {
        return "SubGroup{" +
                "sid=" + sid +
                ", qno=" + qno +
                ", sname='" + sname + '\'' +
                ", createTime=" + createTime +
                ", attach='" + attach + '\'' +
                '}';
    }
}