package com.roy.model;

import java.io.Serializable;
import java.util.Date;

public class UserGroup  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.ugid
     *
     * @mbg.generated
     */
    private Long ugid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.qno
     *
     * @mbg.generated
     */
    private Long qno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.gno
     *
     * @mbg.generated
     */
    private Long gno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.join_time
     *
     * @mbg.generated
     */
    private Date joinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.attach
     *
     * @mbg.generated
     */
    private String attach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.ugid
     *
     * @return the value of user_group.ugid
     *
     * @mbg.generated
     */
    public Long getUgid() {
        return ugid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.ugid
     *
     * @param ugid the value for user_group.ugid
     *
     * @mbg.generated
     */
    public void setUgid(Long ugid) {
        this.ugid = ugid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.qno
     *
     * @return the value of user_group.qno
     *
     * @mbg.generated
     */
    public Long getQno() {
        return qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.qno
     *
     * @param qno the value for user_group.qno
     *
     * @mbg.generated
     */
    public void setQno(Long qno) {
        this.qno = qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.gno
     *
     * @return the value of user_group.gno
     *
     * @mbg.generated
     */
    public Long getGno() {
        return gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.gno
     *
     * @param gno the value for user_group.gno
     *
     * @mbg.generated
     */
    public void setGno(Long gno) {
        this.gno = gno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.duty
     *
     * @return the value of user_group.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.duty
     *
     * @param duty the value for user_group.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.join_time
     *
     * @return the value of user_group.join_time
     *
     * @mbg.generated
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.join_time
     *
     * @param joinTime the value for user_group.join_time
     *
     * @mbg.generated
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.attach
     *
     * @return the value of user_group.attach
     *
     * @mbg.generated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.attach
     *
     * @param attach the value for user_group.attach
     *
     * @mbg.generated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }
}