package com.roy.mapper;

import com.roy.model.ChatInfo;
import com.roy.model.ChatInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChatInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    long countByExample(ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int deleteByExample(ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int insert(ChatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int insertSelective(ChatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    List<ChatInfo> selectByExample(ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    ChatInfo selectByPrimaryKey(Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatInfo record, @Param("example") ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatInfo record, @Param("example") ChatInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatInfo record);

    List<ChatInfo> selectByPage(@Param("start") int start,@Param("size") Integer size,@Param("receiveQno") Long rid,@Param("sendQno") Long sid);

    int markRead(@Param("isread")int mark,@Param("sendQno") Long sendQno,@Param("receiveQno") Long reciveQno);
}