package com.roy.mapper;

import com.roy.model.GroupInfo;
import com.roy.model.GroupInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    long countByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int deleteByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int insert(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int insertSelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    List<GroupInfo> selectByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    GroupInfo selectByPrimaryKey(Long gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupInfo record);
}