package com.roy.mapper;

import com.roy.model.SubGroup;
import com.roy.model.SubGroupExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SubGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    long countByExample(SubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int deleteByExample(SubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int insert(SubGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int insertSelective(SubGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    List<SubGroup> selectByExample(SubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    SubGroup selectByPrimaryKey(Long sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SubGroup record, @Param("example") SubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SubGroup record, @Param("example") SubGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SubGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subgroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SubGroup record);
}