package com.roy.model;

import java.util.Date;

public class ChatInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.cid
     *
     * @mbg.generated
     */
    private Long cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.send_qno
     *
     * @mbg.generated
     */
    private Long sendQno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.receive_qno
     *
     * @mbg.generated
     */
    private Long receiveQno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.isread
     *
     * @mbg.generated
     */
    private Boolean isread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_info.attach
     *
     * @mbg.generated
     */
    private String attach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.cid
     *
     * @return the value of chat_info.cid
     *
     * @mbg.generated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.cid
     *
     * @param cid the value for chat_info.cid
     *
     * @mbg.generated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.send_qno
     *
     * @return the value of chat_info.send_qno
     *
     * @mbg.generated
     */
    public Long getSendQno() {
        return sendQno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.send_qno
     *
     * @param sendQno the value for chat_info.send_qno
     *
     * @mbg.generated
     */
    public void setSendQno(Long sendQno) {
        this.sendQno = sendQno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.receive_qno
     *
     * @return the value of chat_info.receive_qno
     *
     * @mbg.generated
     */
    public Long getReceiveQno() {
        return receiveQno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.receive_qno
     *
     * @param receiveQno the value for chat_info.receive_qno
     *
     * @mbg.generated
     */
    public void setReceiveQno(Long receiveQno) {
        this.receiveQno = receiveQno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.message
     *
     * @return the value of chat_info.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.message
     *
     * @param message the value for chat_info.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.send_time
     *
     * @return the value of chat_info.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.send_time
     *
     * @param sendTime the value for chat_info.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.isread
     *
     * @return the value of chat_info.isread
     *
     * @mbg.generated
     */
    public Boolean getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.isread
     *
     * @param isread the value for chat_info.isread
     *
     * @mbg.generated
     */
    public void setIsread(Boolean isread) {
        this.isread = isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.status
     *
     * @return the value of chat_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.status
     *
     * @param status the value for chat_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_info.attach
     *
     * @return the value of chat_info.attach
     *
     * @mbg.generated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_info.attach
     *
     * @param attach the value for chat_info.attach
     *
     * @mbg.generated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }
}