package com.roy.model;

import java.util.Date;

public class FriendsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_info.fid
     *
     * @mbg.generated
     */
    private Long fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_info.qno
     *
     * @mbg.generated
     */
    private Long qno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_info.fno
     *
     * @mbg.generated
     */
    private Long fno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_info.sid
     *
     * @mbg.generated
     */
    private Long sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_info.add_time
     *
     * @mbg.generated
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_info.attach
     *
     * @mbg.generated
     */
    private String attach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_info.fid
     *
     * @return the value of friends_info.fid
     *
     * @mbg.generated
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_info.fid
     *
     * @param fid the value for friends_info.fid
     *
     * @mbg.generated
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_info.qno
     *
     * @return the value of friends_info.qno
     *
     * @mbg.generated
     */
    public Long getQno() {
        return qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_info.qno
     *
     * @param qno the value for friends_info.qno
     *
     * @mbg.generated
     */
    public void setQno(Long qno) {
        this.qno = qno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_info.fno
     *
     * @return the value of friends_info.fno
     *
     * @mbg.generated
     */
    public Long getFno() {
        return fno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_info.fno
     *
     * @param fno the value for friends_info.fno
     *
     * @mbg.generated
     */
    public void setFno(Long fno) {
        this.fno = fno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_info.sid
     *
     * @return the value of friends_info.sid
     *
     * @mbg.generated
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_info.sid
     *
     * @param sid the value for friends_info.sid
     *
     * @mbg.generated
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_info.add_time
     *
     * @return the value of friends_info.add_time
     *
     * @mbg.generated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_info.add_time
     *
     * @param addTime the value for friends_info.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_info.attach
     *
     * @return the value of friends_info.attach
     *
     * @mbg.generated
     */
    public String getAttach() {
        return attach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_info.attach
     *
     * @param attach the value for friends_info.attach
     *
     * @mbg.generated
     */
    public void setAttach(String attach) {
        this.attach = attach == null ? null : attach.trim();
    }
}